This Is Data Extraction for Transjakarta Trasportation 2021

In [1]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import datetime
import warnings
warnings.filterwarnings('ignore')

In [2]:
#change directory
os.chdir('D:\Data Machinelearning\Transjakarta\CSVTJ')

In [3]:
#list all files csv in directory
csv_files = [f for f in os.listdir() if f.endswith('.csv')]

In [4]:
#read all csv files
dfs = []

for csv in csv_files:
    df = pd.read_csv(csv)
    dfs.append(df)

In [5]:
#concat all csv files
final_df = pd.concat(dfs, ignore_index=True)

In [6]:
#checking data
final_df.head()

,tahun,bulan,jenis,kode_trayek,trayek,jumlah_penumpang
0,2021,8,Mikrotrans,JAK.88,Terminal Tanjung Priok - Ancol Barat,20245
1,2021,8,Mikrotrans,JAK.85,Bintara - Cipinang Indah,19989
2,2021,8,Mikrotrans,JAK.84,Terminal Kampung Melayu - Kapin Raya,33638
3,2021,8,Mikrotrans,JAK.80,Rawa Buaya - Rawa Kompeni,46653
4,2021,8,Mikrotrans,JA.77,Tanjung Priok - Jembatan Item,47157

In [7]:
#check info data
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1473 entries, 0 to 1472
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   tahun             1473 non-null   int64
 1   bulan             1473 non-null   int64
 2   jenis             1473 non-null   object
 3   kode_trayek       1473 non-null   object
 4   trayek            1471 non-null   object
 5   jumlah_penumpang  1473 non-null   int64
dtypes: int64(3), object(3)
memory usage: 69.2+ KB

In [8]:
#checking zero value
filter_data = final_df[final_df.isin([0]).any(1)]

In [9]:
#print zero value
filter_data

,tahun,bulan,jenis,kode_trayek,trayek,jumlah_penumpang
89,2021,8,Angkutan Umum Integrasi,8C,Kebayoran Lama - Tanah Abang,0
94,2021,8,Angkutan Umum Integrasi,6R,Ragunan - Stasin MRT Fatmawati,0
114,2021,8,Angkutan Umum Integrasi,1B,Stasiun Palmerah - Tosari,0
327,2021,12,Angkutan Umum Integrasi,9H,Cipedak - Blok M,0
328,2021,12,Angkutan Umum Integrasi,9E,Kebayoran Lama - Jelambar,0
329,2021,12,Angkutan Umum Integrasi,9D,Pasar Minggu - Tanah Abang,0
330,2021,12,Angkutan Umum Integrasi,8K,Batu Sari-Tanah Abang,0
331,2021,12,Angkutan Umum Integrasi,8E,Bintaro - Blok M,0
332,2021,12,Angkutan Umum Integrasi,8D,Joglo - Blok M,0
333,2021,12,Angkutan Umum Integrasi,8C,Kebayoran Lama - Tanah Abang,0
334,2021,12,Angkutan Umum Integrasi,7P,Pondok Kelapa - BKN,0
335,2021,12,Angkutan Umum Integrasi,7D,Pancoran - TMII,0
336,2021,12,Angkutan Umum Integrasi,7B,Kampung Rambutan - Blok M,0
337,2021,12,Angkutan Umum Integrasi,7A,Kampung Rambutan - Lebak Bulus,0
338,2021,12,Angkutan Umum Integrasi,6R,Ragunan - Stasin MRT Fatmawati,0
339,2021,12,Angkutan Umum Integrasi,6N,Ragunan - Blok M via Kemang,0
340,2021,12,Angkutan Umum Integrasi,6M,Stasiun Manggarai - Blok M,0
342,2021,12,Angkutan Umum Integrasi,6C,Stasin Tebet - Karet via Patra Kuningan,0
343,2021,12,Angkutan Umum Integrasi,5M,Kampung Melayu - Tanah Abang via Cikini,0
344,2021,12,Angkutan Umum Integrasi,5F,Kampung Melayu - Tanah Abang,0
345,2021,12,Angkutan Umum Integrasi,5B,Stasiun Tebet - Bidara Cina,0
346,2021,12,Angkutan Umum Integrasi,4F,Pinang Ranti - Pulo Gadung,0
347,2021,12,Angkutan Umum Integrasi,4B,Stasiun Manggarai - UI,0
348,2021,12,Angkutan Umum Integrasi,3E,Sentraland Cengkareng - Puri Kembangan,0
350,2021,12,Angkutan Umum Integrasi,1Q,Rempoa - Blok M,0
351,2021,12,Angkutan Umum Integrasi,1P,Senen - Bundaran Senayan,0
352,2021,12,Angkutan Umum Integrasi,1N,Tanah Abang - Blok M,0
353,2021,12,Angkutan Umum Integrasi,1M,Meruya - Blok M,0
354,2021,12,Angkutan Umum Integrasi,1H,Tanah Abang - Stasiun Gondangdia,0
355,2021,12,Angkutan Umum Integrasi,1F,Stasiun Palmerah - Bundaran Senayan,0
356,2021,12,Angkutan Umum Integrasi,1E,Pondok Labu - Blok M,0
357,2021,12,Angkutan Umum Integrasi,1C,Pesanggrahan - Blok M,0
358,2021,12,Angkutan Umum Integrasi,1B,Stasiun Palmerah - Tosari,0
359,2021,12,Angkutan Umum Integrasi,1A,PIK - Balai Kota,0
360,2021,12,Angkutan Umum Integrasi,12B,Pluit - Senen,0
361,2021,12,Angkutan Umum Integrasi,11Q,Kampung Melayu - Pulo Gebang via BKT,0
362,2021,12,Angkutan Umum Integrasi,11D,Pulo Gebang - Pulo Gadung 2 via PIK,0
363,2021,12,Angkutan Umum Integrasi,10K,Tanjung Priok - Senen via Taman BMW,0
1191,2021,11,Angkutan Umum Integrasi,8C,Kebayoran Lama - Tanah Abang,0
1196,2021,11,Angkutan Umum Integrasi,6R,Ragunan - Stasin MRT Fatmawati,0
1217,2021,11,Angkutan Umum Integrasi,1F,Stasiun Palmerah - Bundaran Senayan,0
1318,2021,10,Angkutan Umum Integrasi,8C,Kebayoran Lama - Tanah Abang,0
1323,2021,10,Angkutan Umum Integrasi,6R,Ragunan - Stasin MRT Fatmawati,0
1340,2021,10,Angkutan Umum Integrasi,1F,Stasiun Palmerah - Bundaran Senayan,0
1440,2021,9,Angkutan Umum Integrasi,8C,Kebayoran Lama - Tanah Abang,0
1445,2021,9,Angkutan Umum Integrasi,6R,Ragunan - Stasin MRT Fatmawati,0
1462,2021,9,Angkutan Umum Integrasi,1F,Stasiun Palmerah - Bundaran Senayan,0

Dari Hasil Tabel Diatas Pada Data Transjakarta masih terdapat nilai 0 untuk menghindari bias pada hasil analis maka pada bulan desember tidak akan digunakan karna terlalu banyak data yang 0 serta pada bulan 8,9,10,11 Trayek 8C,6R,1F saja yang datanya 0 maka ketiga trayek tersebut tidak akan diikutsertakan dikarenakan tidak memiliki data jumlah penumpang di bulan tersebut

In [10]:
#change directory new folder
os.chdir('D:\Data Machinelearning\Transjakarta\CSVTJFinal')

In [11]:
#list all files csv in directory
csv_files = [f for f in os.listdir() if f.endswith('.csv')]

In [12]:
#read all csv files
dfsf = []

for csv in csv_files:
    df = pd.read_csv(csv)
    dfsf.append(df)

In [13]:
#concat all csv files
final_df= pd.concat(dfsf, ignore_index=True)

In [14]:
#checking drop zero value
clean_df = final_df.drop(final_df[final_df['jumlah_penumpang']==0].index)

In [15]:
#sorting data to bulan
clean_df.sort_values(by=['bulan'], inplace=True,ignore_index=True)

In [16]:
#checking info data
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2678 entries, 0 to 2677
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   tahun             2678 non-null   int64
 1   bulan             2678 non-null   int64
 2   jenis             2678 non-null   object
 3   kode_trayek       2678 non-null   object
 4   trayek            2678 non-null   object
 5   jumlah_penumpang  2678 non-null   int64
dtypes: int64(3), object(3)
memory usage: 125.7+ KB

In [17]:
#checking info data
clean_df.tail()

,tahun,bulan,jenis,kode_trayek,trayek,jumlah_penumpang
2673,2021,11,Mikrotrans,JAK.33,Pulo Gadung - Kota,64400
2674,2021,11,Mikrotrans,JAK.34,Rawamangun - Klender,71939
2675,2021,11,Mikrotrans,JAK.35,Pangkalan Jati - Rawamangun,34484
2676,2021,11,Mikrotrans,JAK.21,Cililitan - Dwikora,77867
2677,2021,11,Angkutan Umum Integrasi,11D,Pulo Gebang - Pulo Gadung 2 via PIK,59155

In [ ]:
#table to csv
clean_df.to_csv('DataTransjakarta.csv', index=False)

In [18]:
#spliting variable trayek with delimiter '-'
splited_df = clean_df['trayek'].str.split(' - ', expand=True)

In [19]:
#checking the value
splited_df

                    0                      1
0         Tanah Abang                  Kota
1            Pancoran                   TMII
2       Pondok Kelapa                    BKN
3      Kebayoran Lama            Tanah Abang
4               Joglo                 Blok M
...               ...                    ...
2673      Pulo Gadung                   Kota
2674       Rawamangun                Klender
2675  Pangkalan  Jati             Rawamangun
2676        Cililitan                Dwikora
2677      Pulo Gebang  Pulo Gadung 2 via PIK

[2678 rows x 2 columns]

In [ ]:
#spliting variable trayek with delimiter 'via'
splited_df2=splited_df[1].str.split(' via ', expand=True)

In [21]:
#checking data info
splited_df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2678 entries, 0 to 2677
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       2638 non-null   object
 1   1       406 non-null    object
dtypes: object(2)
memory usage: 42.0+ KB

In [22]:
#add the new variable to dataframe
clean_df['tempat_awal']=splited_df[0]
clean_df['tempat_akhir']=splited_df2[0]
clean_df['via']=splited_df2[1]

In [23]:
#checking data info
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2678 entries, 0 to 2677
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   tahun             2678 non-null   int64
 1   bulan             2678 non-null   int64
 2   jenis             2678 non-null   object
 3   kode_trayek       2678 non-null   object
 4   trayek            2678 non-null   object
 5   jumlah_penumpang  2678 non-null   int64
 6   tempat_awal       2678 non-null   object
 7   tempat_akhir      2638 non-null   object
 8   via               406 non-null    object
dtypes: int64(3), object(6)
memory usage: 188.4+ KB

In [24]:
#from table to csv
clean_df.to_csv('Transjakarta2.csv', index=False)